#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/ctrlpvim/ctrlp.vim.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/mxw/vim-jsx.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/benekastah/neomake.git",
  "git://github.com/leafgarland/typescript-vim.git",
  "git://github.com/chriskempson/base16-vim.git",
  "git://github.com/jdonaldson/vaxe.git",
  "git://github.com/wakatime/vim-wakatime.git",
  "git://github.com/guns/vim-clojure-static.git",
  "git://github.com/guns/vim-sexp.git",
  "git://github.com/tpope/vim-sexp-mappings-for-regular-people.git",
  "git://github.com/tpope/vim-fireplace.git",
  "git://github.com/junegunn/rainbow_parentheses.vim.git",
  "git://github.com/sbdchd/neoformat",
]

vim_org_scripts = [ ]

zip_files = { }

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

expected_bundles = git_bundles.map{|b| File.basename(b, '.git')}
existing_bundles = Dir["*"].each{|d| File.basename(d)}

old_bundles = existing_bundles - expected_bundles

old_bundles.each do |d|
  puts "=====> Removing #{d}"
  FileUtils.rm_rf d
end

git_bundles.zip(expected_bundles) do |url, dir|
  if File.exists?(dir)
    puts "=====> Updating #{dir}"
    FileUtils.cd(dir) do
      `git pull --ff-only`
    end
  else
    puts "=====> Installing #{dir}"
    `git clone --depth 1 #{url} #{dir}`
  end
end

zip_files.each do |name, url|
  puts "  Downloading zip #{name}"
  local_file = "#{name}.zip"
  FileUtils.mkdir_p(name)
  File.open(local_file, "w") do |file|
    file << open(url).read
  end
  `unzip #{local_file} -d #{name}`
  FileUtils.rm(local_file)
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
